### ISSUE TITLE
Error compile <engine name="android" spec="~8.0.0" />

### ISSUE THREAD

**Issue by dinami-k** [darryncampbell/EnterpriseBarcodePoC#3]
Hi, Error build in phonegapbuild

Thanks a lot.

**My config.xml**

  <access origin="*" />

  <allow-navigation href="*" />

  <allow-intent href="*" />
  <allow-intent href="http://*/*" />
  <allow-intent href="https://*/*" />
  <allow-intent href="tel:*" />
  <allow-intent href="sms:*" />
  <allow-intent href="mailto:*" />
  <allow-intent href="geo:*" />

  <feature name="http://api.phonegap.com/1.0/network" />
  <feature name="http://api.phonegap.com/1.0/camera" />
  <feature name="http://api.phonegap.com/1.0/notification" />

  <platform name="android">
    <allow-intent href="market:*" />
  </platform>
  <gap:plugin name="com-darryncampbell-enterprisebarcode" source="npm" />
  <plugin name="com-darryncampbell-cordova-plugin-intent" spec="^1.0.0" />
  <engine name="android" spec="~8.0.0" />

**Log Error PhoneGap Build:**

Build Date: 2020-01-24 16:51:28 +0000
--------------------------------------------------------------------------------
PREPARE OUTPUT
--------------------------------------------------------------------------------
Generating platform-specific config.xml from defaults for android at /var/gimlet/tmp/47200748979500/1477208/app/src/main/res/xml/config.xml
Merging project's config.xml into platform-specific android config.xml
[Gradle Properties] Preparing Configuration
[Gradle Properties] File missing, creating file with Cordova defaults.
[Gradle Properties] Appending default configuration properties
[Gradle Properties] Appending configuration item: org.gradle.daemon=true
[Gradle Properties] Appending configuration item: org.gradle.jvmargs=-Xmx2048m
[Gradle Properties] Appending configuration item: android.useDeprecatedNdk=true
[Gradle Properties] Appending custom configuration properties
[Gradle Properties] Updating and Saving File
Merging and updating files from [, ../platform_www] to ../app/src/main/assets/www
  copy  admision.html ../app/src/main/assets/www/admision.html (new file)
  copy  admisionpuerta.html ../app/src/main/assets/www/admisionpuerta.html (new file)
  copy  config.xml ../app/src/main/assets/www/config.xml (new file)
  copy  configurarapp.html ../app/src/main/assets/www/configurarapp.html (new file)
  copy  configurarapp_old.html ../app/src/main/assets/www/configurarapp_old.html (new file)
  copy  configurareventoactivo.html ../app/src/main/assets/www/configurareventoactivo.html (new file)
  copy  configurarmodo.html ../app/src/main/assets/www/configurarmodo.html (new file)
  copy  consultaraccesodw.html ../app/src/main/assets/www/consultaraccesodw.html (new file)
  copy  contador.html ../app/src/main/assets/www/contador.html (new file)
  copy  controlaccesocamara.html ../app/src/main/assets/www/controlaccesocamara.html (new file)
  copy  controlaccesocamaravue.html ../app/src/main/assets/www/controlaccesocamaravue.html (new file)
  copy  controlaccesodw.html ../app/src/main/assets/www/controlaccesodw.html (new file)
  copy  controlaccesodw2.html ../app/src/main/assets/www/controlaccesodw2.html (new file)
  copy  controlaccesodw3.html ../app/src/main/assets/www/controlaccesodw3.html (new file)
  copy  controlaccesodw_old.html ../app/src/main/assets/www/controlaccesodw_old.html (new file)
  copy  controlaccesotextbox.html ../app/src/main/assets/www/controlaccesotextbox.html (new file)
  copy  controladmisiondni.html ../app/src/main/assets/www/controladmisiondni.html (new file)
  copy  controlenfermeriadni.html ../app/src/main/assets/www/controlenfermeriadni.html (new file)
  mkdir ../app/src/main/assets/www/cordova-js-src
  mkdir ../app/src/main/assets/www/cordova-js-src/android
  copy  ../platform_www/cordova-js-src/android/nativeapiprovider.js ../app/src/main/assets/www/cordova-js-src/android/nativeapiprovider.js (new file)
  copy  ../platform_www/cordova-js-src/android/promptbasednativeapi.js ../app/src/main/assets/www/cordova-js-src/android/promptbasednativeapi.js (new file)
  copy  ../platform_www/cordova-js-src/exec.js ../app/src/main/assets/www/cordova-js-src/exec.js (new file)
  copy  ../platform_www/cordova-js-src/platform.js ../app/src/main/assets/www/cordova-js-src/platform.js (new file)
  mkdir ../app/src/main/assets/www/cordova-js-src/plugin
  mkdir ../app/src/main/assets/www/cordova-js-src/plugin/android
  copy  ../platform_www/cordova-js-src/plugin/android/app.js ../app/src/main/assets/www/cordova-js-src/plugin/android/app.js (new file)
  copy  ../platform_www/cordova.js ../app/src/main/assets/www/cordova.js (updated file)
  copy  css/all.min.css ../app/src/main/assets/www/css/all.min.css (new file)
  copy  css/bootstrap.min.css ../app/src/main/assets/www/css/bootstrap.min.css (new file)
  copy  css/control-acceso.css ../app/src/main/assets/www/css/control-acceso.css (new file)
  copy  css/core-colors.css ../app/src/main/assets/www/css/core-colors.css (new file)
  copy  css/core-colors.min.css ../app/src/main/assets/www/css/core-colors.min.css (new file)
  copy  css/core-icons.css ../app/src/main/assets/www/css/core-icons.css (new file)
  copy  css/core-icons.min.css ../app/src/main/assets/www/css/core-icons.min.css (new file)
  copy  css/core.css ../app/src/main/assets/www/css/core.css (new file)
  copy  css/core.min.css ../app/src/main/assets/www/css/core.min.css (new file)
  copy  css/iguazujungle.css ../app/src/main/assets/www/css/iguazujungle.css (new file)
  delete ../app/src/main/assets/www/css/index.css (no source)
  copy  css/mobile.css ../app/src/main/assets/www/css/mobile.css (new file)
  copy  css/select2.min.css ../app/src/main/assets/www/css/select2.min.css (new file)
  copy  dashboard.html ../app/src/main/assets/www/dashboard.html (new file)
  copy  dashboardn.html ../app/src/main/assets/www/dashboardn.html (new file)
  copy  dashboardsalida.html ../app/src/main/assets/www/dashboardsalida.html (new file)
  copy  dniexportar.html ../app/src/main/assets/www/dniexportar.html (new file)
  copy  espectadores.html ../app/src/main/assets/www/espectadores.html (new file)
  mkdir ../app/src/main/assets/www/fonts
  copy  fonts/Roboto-bold.woff ../app/src/main/assets/www/fonts/Roboto-bold.woff (new file)
  copy  fonts/Roboto-light.woff ../app/src/main/assets/www/fonts/Roboto-light.woff (new file)
  copy  fonts/Roboto-medium.woff ../app/src/main/assets/www/fonts/Roboto-medium.woff (new file)
  copy  fonts/Roboto-regular.woff ../app/src/main/assets/www/fonts/Roboto-regular.woff (new file)
  copy  fonts/core-icons.json ../app/src/main/assets/www/fonts/core-icons.json (new file)
  copy  fonts/core-icons.svg ../app/src/main/assets/www/fonts/core-icons.svg (new file)
  copy  fonts/core-icons.ttf ../app/src/main/assets/www/fonts/core-icons.ttf (new file)
  copy  fonts/core-icons.woff ../app/src/main/assets/www/fonts/core-icons.woff (new file)
  copy  historial.html ../app/src/main/assets/www/historial.html (new file)
  copy  historialoffline.html ../app/src/main/assets/www/historialoffline.html (new file)
  copy  home.html ../app/src/main/assets/www/home.html (new file)
  copy  home.html.old ../app/src/main/assets/www/home.html.old (new file)
  copy  icon.png ../app/src/main/assets/www/icon.png (new file)
  mkdir ../app/src/main/assets/www/image
  copy  image/bkg-menu.png ../app/src/main/assets/www/image/bkg-menu.png (new file)
  copy  image/icon.png ../app/src/main/assets/www/image/icon.png (new file)
  delete ../app/src/main/assets/www/img (no source)
  delete ../app/src/main/assets/www/img/cordova.png (no source)
  delete ../app/src/main/assets/www/img/logo.png (no source)
  copy  index - Copy.html ../app/src/main/assets/www/index - Copy.html (new file)
  copy  index.html ../app/src/main/assets/www/index.html (updated file)
  copy  index.html.old ../app/src/main/assets/www/index.html.old (new file)
  copy  ingreso.html ../app/src/main/assets/www/ingreso.html (new file)
  copy  ingresopuerta.html ../app/src/main/assets/www/ingresopuerta.html (new file)
  copy  ingresorango.html ../app/src/main/assets/www/ingresorango.html (new file)
  copy  iniciarembarque.html ../app/src/main/assets/www/iniciarembarque.html (new file)
  mkdir ../app/src/main/assets/www/jps
  copy  jps/dw.js ../app/src/main/assets/www/jps/dw.js (new file)
  copy  jps/handlebars.js ../app/src/main/assets/www/jps/handlebars.js (new file)
  copy  jps/nfc.js ../app/src/main/assets/www/jps/nfc.js (new file)
  copy  jps/nfcdw.js ../app/src/main/assets/www/jps/nfcdw.js (new file)
  copy  jps/scripts.js ../app/src/main/assets/www/jps/scripts.js (new file)
  copy  jps/vue.js ../app/src/main/assets/www/jps/vue.js (new file)
  copy  jps/vue.min.js ../app/src/main/assets/www/jps/vue.min.js (new file)
  copy  js/Chart.PieceLabel.min.js ../app/src/main/assets/www/js/Chart.PieceLabel.min.js (new file)
  copy  js/chart.js ../app/src/main/assets/www/js/chart.js (new file)
  copy  js/chart.min.js ../app/src/main/assets/www/js/chart.min.js (new file)
  copy  js/core.js ../app/src/main/assets/www/js/core.js (new file)
  copy  js/core.min.js ../app/src/main/assets/www/js/core.min.js (new file)
  copy  js/dw.js ../app/src/main/assets/www/js/dw.js (new file)
  delete ../app/src/main/assets/www/js/index.js (no source)
  copy  js/jquery-3.1.1.min.js ../app/src/main/assets/www/js/jquery-3.1.1.min.js (new file)
  copy  js/jquery.cookie.js ../app/src/main/assets/www/js/jquery.cookie.js (new file)
  copy  js/jquery.signalR-2.2.3.js ../app/src/main/assets/www/js/jquery.signalR-2.2.3.js (new file)
  mkdir ../app/src/main/assets/www/js/jqueryui
  copy  js/jqueryui/AUTHORS.txt ../app/src/main/assets/www/js/jqueryui/AUTHORS.txt (new file)
  copy  js/jqueryui/LICENSE.txt ../app/src/main/assets/www/js/jqueryui/LICENSE.txt (new file)
  mkdir ../app/src/main/assets/www/js/jqueryui/images
  copy  js/jqueryui/images/ui-bg_glass_75_d0e5f5_1x400.png ../app/src/main/assets/www/js/jqueryui/images/ui-bg_glass_75_d0e5f5_1x400.png (new file)
  copy  js/jqueryui/images/ui-bg_glass_85_dfeffc_1x400.png ../app/src/main/assets/www/js/jqueryui/images/ui-bg_glass_85_dfeffc_1x400.png (new file)
  copy  js/jqueryui/images/ui-bg_glass_95_fef1ec_1x400.png ../app/src/main/assets/www/js/jqueryui/images/ui-bg_glass_95_fef1ec_1x400.png (new file)
  copy  js/jqueryui/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png ../app/src/main/assets/www/js/jqueryui/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png (new file)
  copy  js/jqueryui/images/ui-bg_inset-hard_100_f5f8f9_1x100.png ../app/src/main/assets/www/js/jqueryui/images/ui-bg_inset-hard_100_f5f8f9_1x100.png (new file)
  copy  js/jqueryui/images/ui-bg_inset-hard_100_fcfdfd_1x100.png ../app/src/main/assets/www/js/jqueryui/images/ui-bg_inset-hard_100_fcfdfd_1x100.png (new file)
  copy  js/jqueryui/images/ui-icons_217bc0_256x240.png ../app/src/main/assets/www/js/jqueryui/images/ui-icons_217bc0_256x240.png (new file)
  copy  js/jqueryui/images/ui-icons_2e83ff_256x240.png ../app/src/main/assets/www/js/jqueryui/images/ui-icons_2e83ff_256x240.png (new file)
  copy  js/jqueryui/images/ui-icons_469bdd_256x240.png ../app/src/main/assets/www/js/jqueryui/images/ui-icons_469bdd_256x240.png (new file)
  copy  js/jqueryui/images/ui-icons_6da8d5_256x240.png ../app/src/main/assets/www/js/jqueryui/images/ui-icons_6da8d5_256x240.png (new file)
  copy  js/jqueryui/images/ui-icons_cd0a0a_256x240.png ../app/src/main/assets/www/js/jqueryui/images/ui-icons_cd0a0a_256x240.png (new file)
  copy  js/jqueryui/images/ui-icons_d8e7f3_256x240.png ../app/src/main/assets/www/js/jqueryui/images/ui-icons_d8e7f3_256x240.png (new file)
  copy  js/jqueryui/images/ui-icons_f9bd01_256x240.png ../app/src/main/assets/www/js/jqueryui/images/ui-icons_f9bd01_256x240.png (new file)
  copy  js/jqueryui/index.html ../app/src/main/assets/www/js/jqueryui/index.html (new file)
  copy  js/jqueryui/jquery-ui.css ../app/src/main/assets/www/js/jqueryui/jquery-ui.css (new file)
  copy  js/jqueryui/jquery-ui.js ../app/src/main/assets/www/js/jqueryui/jquery-ui.js (new file)
  copy  js/jqueryui/jquery-ui.min.css ../app/src/main/assets/www/js/jqueryui/jquery-ui.min.css (new file)
  copy  js/jqueryui/jquery-ui.min.js ../app/src/main/assets/www/js/jqueryui/jquery-ui.min.js (new file)
  copy  js/jqueryui/jquery-ui.structure.css ../app/src/main/assets/www/js/jqueryui/jquery-ui.structure.css (new file)
  copy  js/jqueryui/jquery-ui.structure.min.css ../app/src/main/assets/www/js/jqueryui/jquery-ui.structure.min.css (new file)
  copy  js/jqueryui/jquery-ui.theme.css ../app/src/main/assets/www/js/jqueryui/jquery-ui.theme.css (new file)
  copy  js/jqueryui/jquery-ui.theme.min.css ../app/src/main/assets/www/js/jqueryui/jquery-ui.theme.min.css (new file)
  copy  js/jqueryui/package.json ../app/src/main/assets/www/js/jqueryui/package.json (new file)
  copy  js/select2.min.js ../app/src/main/assets/www/js/select2.min.js (new file)
  copy  kilowatts - Copy.html ../app/src/main/assets/www/kilowatts - Copy.html (new file)
  copy  kilowatts.html ../app/src/main/assets/www/kilowatts.html (new file)
  copy  log.html ../app/src/main/assets/www/log.html (new file)
  copy  logapierror.html ../app/src/main/assets/www/logapierror.html (new file)
  copy  nfc.html ../app/src/main/assets/www/nfc.html (new file)
  copy  novedades.html ../app/src/main/assets/www/novedades.html (new file)
  mkdir ../app/src/main/assets/www/scripts
  copy  scripts/_references.js ../app/src/main/assets/www/scripts/_references.js (new file)
  copy  scripts/bootstrap.min.js ../app/src/main/assets/www/scripts/bootstrap.min.js (new file)
  copy  scripts/ingresohora.js ../app/src/main/assets/www/scripts/ingresohora.js (new file)
  copy  scripts/instascan.min.js ../app/src/main/assets/www/scripts/instascan.min.js (new file)
  copy  scripts/jps.common.js ../app/src/main/assets/www/scripts/jps.common.js (new file)
  copy  scripts/jps.dashboard.admision.js ../app/src/main/assets/www/scripts/jps.dashboard.admision.js (new file)
  copy  scripts/jps.dashboard.admisionpuerta.js ../app/src/main/assets/www/scripts/jps.dashboard.admisionpuerta.js (new file)
  copy  scripts/jps.dashboard.general.js ../app/src/main/assets/www/scripts/jps.dashboard.general.js (new file)
  copy  scripts/jps.dashboard.ingreso.js ../app/src/main/assets/www/scripts/jps.dashboard.ingreso.js (new file)
  copy  scripts/jps.dashboard.ingresopuerta.js ../app/src/main/assets/www/scripts/jps.dashboard.ingresopuerta.js (new file)
  copy  scripts/jps.dashboard.ingresorango.js ../app/src/main/assets/www/scripts/jps.dashboard.ingresorango.js (new file)
  copy  scripts/jps.dashboard.salida.js ../app/src/main/assets/www/scripts/jps.dashboard.salida.js (new file)
  copy  scripts/jps.dashboard.sector.js ../app/src/main/assets/www/scripts/jps.dashboard.sector.js (new file)
  copy  scripts/jps.dashboard.sectorsalida.js ../app/src/main/assets/www/scripts/jps.dashboard.sectorsalida.js (new file)
  copy  scripts/jps.dashboard.signalr.js ../app/src/main/assets/www/scripts/jps.dashboard.signalr.js (new file)
  copy  scripts/jps.mobile.js ../app/src/main/assets/www/scripts/jps.mobile.js (new file)
  copy  scripts/jps.models.js ../app/src/main/assets/www/scripts/jps.models.js (new file)
  copy  scripts/jps.phonegap.js ../app/src/main/assets/www/scripts/jps.phonegap.js (new file)
  copy  scripts/jquery-3.4.1.slim.min.js ../app/src/main/assets/www/scripts/jquery-3.4.1.slim.min.js (new file)
  copy  scripts/md5.pack.js ../app/src/main/assets/www/scripts/md5.pack.js (new file)
  copy  sector.html ../app/src/main/assets/www/sector.html (new file)
  copy  sectorrango.html ../app/src/main/assets/www/sectorrango.html (new file)
  copy  sectorsalida.html ../app/src/main/assets/www/sectorsalida.html (new file)
  copy  splash.png ../app/src/main/assets/www/splash.png (new file)
  copy  tam.png ../app/src/main/assets/www/tam.png (new file)
  mkdir ../app/src/main/assets/www/webfonts
  copy  webfonts/fa-brands-400.eot ../app/src/main/assets/www/webfonts/fa-brands-400.eot (new file)
  copy  webfonts/fa-brands-400.svg ../app/src/main/assets/www/webfonts/fa-brands-400.svg (new file)
  copy  webfonts/fa-brands-400.ttf ../app/src/main/assets/www/webfonts/fa-brands-400.ttf (new file)
  copy  webfonts/fa-brands-400.woff ../app/src/main/assets/www/webfonts/fa-brands-400.woff (new file)
  copy  webfonts/fa-brands-400.woff2 ../app/src/main/assets/www/webfonts/fa-brands-400.woff2 (new file)
  copy  webfonts/fa-regular-400.eot ../app/src/main/assets/www/webfonts/fa-regular-400.eot (new file)
  copy  webfonts/fa-regular-400.svg ../app/src/main/assets/www/webfonts/fa-regular-400.svg (new file)
  copy  webfonts/fa-regular-400.ttf ../app/src/main/assets/www/webfonts/fa-regular-400.ttf (new file)
  copy  webfonts/fa-regular-400.woff ../app/src/main/assets/www/webfonts/fa-regular-400.woff (new file)
  copy  webfonts/fa-regular-400.woff2 ../app/src/main/assets/www/webfonts/fa-regular-400.woff2 (new file)
  copy  webfonts/fa-solid-900.eot ../app/src/main/assets/www/webfonts/fa-solid-900.eot (new file)
  copy  webfonts/fa-solid-900.svg ../app/src/main/assets/www/webfonts/fa-solid-900.svg (new file)
  copy  webfonts/fa-solid-900.ttf ../app/src/main/assets/www/webfonts/fa-solid-900.ttf (new file)
  copy  webfonts/fa-solid-900.woff ../app/src/main/assets/www/webfonts/fa-solid-900.woff (new file)
  copy  webfonts/fa-solid-900.woff2 ../app/src/main/assets/www/webfonts/fa-solid-900.woff2 (new file)
  copy  webfonts/metapro-bold-webfont.woff ../app/src/main/assets/www/webfonts/metapro-bold-webfont.woff (new file)
  copy  webfonts/metapro-medium-webfont.woff ../app/src/main/assets/www/webfonts/metapro-medium-webfont.woff (new file)
Wrote out android application name "TAM" to /var/gimlet/tmp/47200748979500/1477208/app/src/main/res/values/strings.xml
android-versionCode not found in config.xml. Generating a code based on version in config.xml (4.2.0): 40200
Wrote out Android package name "com.jps.tam" to /var/gimlet/tmp/47200748979500/1477208/app/src/main/java/com/jps/tam/TAM.java
Updating icons at ../app/src/main/res
  copy  icon.png ../app/src/main/res/mipmap-mdpi/ic_launcher.png (new file)
Updating splash screens at ../app/src/main/res
  delete ../app/src/main/res/drawable-land-hdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-ldpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-mdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xxhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xxxhdpi/screen.png (no source)
  copy  splash.png ../app/src/main/res/drawable-mdpi/screen.png (new file)
  delete ../app/src/main/res/drawable-port-hdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-ldpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-mdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xxhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xxxhdpi/screen.png (no source)
This app does not have additional resource files defined
Prepared android project successfully
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "2.0.2" for android
Fetching plugin "cordova-plugin-battery-status" via npm
Installing "cordova-plugin-battery-status" at "2.0.3" for android
Fetching plugin "cordova-plugin-camera" via npm
Installing "cordova-plugin-camera" at "4.1.0" for android
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "cordova-plugin-media-capture" via npm
Installing "cordova-plugin-media-capture" at "3.0.3" for android
Fetching plugin "cordova-plugin-file@^6.0.0" via npm
Installing "cordova-plugin-file" at "6.0.2" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Fetching plugin "cordova-plugin-console" via npm
Installing "cordova-plugin-console" at "1.1.0" for android
Fetching plugin "cordova-plugin-contacts" via npm
Installing "cordova-plugin-contacts" at "3.0.1" for android
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "2.0.3" for android
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs" at "2.0.2" for android
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation" at "4.0.2" for android
Fetching plugin "cordova-plugin-globalization" via npm
Installing "cordova-plugin-globalization" at "1.11.0" for android
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "3.2.0" for android
Fetching plugin "cordova-plugin-media" via npm
Installing "cordova-plugin-media" at "5.0.3" for android
Plugin dependency "cordova-plugin-file@6.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Fetching plugin "cordova-plugin-splashscreen" via npm
Installing "cordova-plugin-splashscreen" at "5.0.3" for android
Fetching plugin "cordova-plugin-vibration" via npm
Installing "cordova-plugin-vibration" at "3.1.1" for android
Fetching plugin "com.verso.cordova.clipboard" via npm
Installing "com.verso.cordova.clipboard" at "0.1.0" for android
Fetching plugin "cordova-plugin-flashlight" via npm
Installing "cordova-plugin-flashlight" at "3.2.0" for android
Fetching plugin "cordova-plugin-compat@^1.0.0" via npm
Installing "cordova-plugin-compat" at "1.2.0" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 8.0.0, failed version requirement: 
      <6.3.0
Skipping 'cordova-plugin-compat' for android
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.4" for android
Fetching plugin "cordova-plugin-keyboard" via npm
Installing "cordova-plugin-keyboard" at "1.2.0" for android
Fetching plugin "phonegap-nfc" via npm
Installing "phonegap-nfc" at "1.0.4" for android
Fetching plugin "com-darryncampbell-enterprisebarcode" via npm
Installing "com.symbol.enterprisebarcode" at "0.0.4" for android
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "com-darryncampbell-cordova-plugin-intent@^1.0.0" via npm
Installing "com-darryncampbell-cordova-plugin-intent" at "1.3.0" for android
Subproject Path: CordovaLib
Subproject Path: app

--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android Studio Gradle projects

# Project target.
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.android.support:support-v4:27.+
cordova.gradle.include.1=com.symbol.enterprisebarcode/tam-extras.gradle
cordova.system.library.2=com.android.support:support-v4:27.1.0
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :app
WARNING: Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Exception while marshalling /opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/28.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/extras/google/instantapps/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platform-tools/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-28/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-29/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/28.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/extras/google/instantapps/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platform-tools/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-28/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-29/package.xml. Probably the SDK is read-only

> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preReleaseBuild UP-TO-DATE
> Task :CordovaLib:checkReleaseManifest
> Task :CordovaLib:processReleaseManifest
> Task :app:preReleaseBuild
> Task :CordovaLib:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :CordovaLib:packageReleaseRenderscript NO-SOURCE
> Task :app:compileReleaseRenderscript
> Task :app:checkReleaseManifest
> Task :app:generateReleaseBuildConfig
> Task :app:prepareLintJar
> Task :app:generateReleaseSources
> Task :CordovaLib:compileReleaseRenderscript
> Task :CordovaLib:generateReleaseBuildConfig
> Task :CordovaLib:generateReleaseResValues
> Task :CordovaLib:generateReleaseResources
> Task :CordovaLib:packageReleaseResources
> Task :CordovaLib:generateReleaseRFile
> Task :CordovaLib:prepareLintJar
> Task :CordovaLib:generateReleaseSources
> Task :CordovaLib:javaPreCompileRelease

> Task :CordovaLib:compileReleaseJavaWithJavac

Note: /var/gimlet/tmp/47200748979500/1477208/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :CordovaLib:processReleaseJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
> Task :app:javaPreCompileRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Failed to transform file 'com.symbol.emdk.jar' to match attributes {artifactType=processed-jar} using transform IdentityTransform
   > Transform output file /var/gimlet/tmp/47200748979500/1477208/app/lib/com.symbol.emdk.jar does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
17 actionable tasks: 17 executed
Error: /var/gimlet/tmp/47200748979500/1477208/gradlew: Command failed with exit code 1 Error output:
Note: /var/gimlet/tmp/47200748979500/1477208/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Failed to transform file 'com.symbol.emdk.jar' to match attributes {artifactType=processed-jar} using transform IdentityTransform
   > Transform output file /var/gimlet/tmp/47200748979500/1477208/app/lib/com.symbol.emdk.jar does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
    at ChildProcess.whenDone (/var/gimlet/tmp/47200748979500/1477208/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by darryncampbell** [comment]
This project is now very old and I would consider it obsolete for most purposes.  I strongly recommend you follow the instructions at https://developer.zebra.com/community/home/blog/2016/08/04/integrating-datawedge-into-your-cordova-application to integrate scanning capabilities into your Cordova app on a Zebra device.  I apologise for the formatting of that post, many of the images got lost recently but the key content is there.
